name: Get prices from opensea

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: db

      - name: Install Dependencies
        run: |
          yarn

      - name: Query for sales and offers
        run: |
          yarn script scripts/queryOpenSea.ts

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitActionBot
          message: Update opensea prices
          branch: db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
